apiVersion: v1
kind: Service
metadata:
  labels:
    app: gocd-server-svc
  name: gocd-server-svc
  namespace: gocd
spec:
  ports:
  - name: gocd-server
    port: 8153
    protocol: TCP
    targetPort: 8153
  selector:
    app: gocd-server
  type: NodePort
